version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,ec2,iam
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/health']
      interval: 10s
      retries: 10
    volumes:
      - ./localstack:/tmp/localstack
